//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public byte[] Archivo { get; set; }
        public string Extension { get; set; }
        public int Pago_id_pago { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
